### ISSUE TITLE
Completing "Receiving Module Assignments Checklist" for Week 1 of Front-end Engineering

### ISSUE THREAD

**Issue by kavuong** [bitprj/gatsby-bitcamp#1]
### Pre-approval Checklist

- [ ] Confirm modules to be done
- [ ] Finalize activities, labs and workshop list
- [ ] Confirm overall project deadline

### Post-approval Checklist
- [ ] Making Epics in a Project [THIS SHOULD BE DONE ASAP post-approval]
  - [ ] If applicable, make modules as Epics on Zenhub
  - [ ] Post activities, labs and workshops on Zenhub as Epics under the appropriate module
- [ ] First week's issues [THIS SHOULD BE DONE ASAP post-approval]
  - [ ] Generate issues that should be completed in the first week
  - [ ] Assign to a milestone for the team
  - [ ] Inform team that their milestone is ready and that it is due in a week
- [ ] Have long-term, week-by-week plan under each activity/lab/workshop Epic describing what should be done by the team each week
- [ ] Generate all issues for all weeks 
  - [ ] Make sure each issue is added to the appropriate Epic
- [ ] Assign Epic Points to each module, activity, lab and workshop
- [ ] Set timeline for module, activity, lab and workshop Epics in Zenhub Calendar

**Deadline**
Mon, 3/30 (Pre-approval)
  * Changed to Wed, 4/1
Wed, 4/1 (Post-approval)
  * Changed to Fri, 4/3

**Comment by kavuong** [comment]
@jeffchhen 

Pre-approval: there should be descriptions behind the module, activities and labs. Right now I fail to see what exactly is the scope of the module, activities and labs without ample textual descriptions. 

Also are there two labs?
https://github.com/bitprj/curriculum/issues/809 and https://github.com/bitprj/curriculum/issues/807

The Weather API Lab and Create an API with Stitch are both extremely vague.

Moreover, adding descriptions will also help future developers and managers to be able to more easily contribute and gain the scope of what the Front-end Engineering BitCamp is all about.
